### ISSUE TITLE
I have found a mismatch vscode. OS X 10.12 macOS Sierra

### ISSUE THREAD

**Issue by DavidStrada** [RealGithub/RealGithub#1]
here's how a piece of code should look like. ( javascript ).

``` javascript

var install = require('./lib/install');
var bundle = require('./lib/bundle');
var core = require('./lib/core');
var ui = require('./lib/ui');
var EventEmitter = require('events').EventEmitter;
var SystemJSLoader = require('systemjs').constructor;
var config = require('./lib/config');
var path = require('path');
var toFileURL = require('./lib/common').toFileURL;

require('rsvp').on('error', function(reason) {
  ui.log('warn', 'Unhandled promise rejection.\n' + reason && reason.stack || reason || '' + '\n');
});

var API = module.exports = new EventEmitter();

API.setPackagePath = function(packagePath) {
  if (config.loaded && process.env.jspmConfigPath !== path.resolve(packagePath, 'package.json'))
    throw new Error('Configuration has already been loaded. Call setPackagePath before using other APIs.');
  process.env.jspmConfigPath = path.resolve(packagePath, 'package.json');
};
API.setPackagePath('.');

```

*\* here's how it looks on VisualStudio Code : **

![Visual Studio Code](https://dl.dropboxusercontent.com/u/13359706/Screen%20Shot%202016-10-21%20at%209.00.57%20PM.png)

*_here's how it looks on Sublime Text 3 : *_

![ST3](https://dl.dropboxusercontent.com/u/13359706/Screen%20Shot%202016-10-21%20at%209.05.45%20PM.png)

**Comment by NoHomey** [comment]
@DavidStrada unfortunately VSCode are using different language syntax grammars than Github, as well supporting different theme scopes ....

I've been playing more than three hours and this is the result:

**_VSCode**_
![vscode](https://cloud.githubusercontent.com/assets/8791438/19618131/bba6adc0-984a-11e6-8f02-7a83f8fd996b.png)

**_tmTheme-Editor**_ (the editor I'm using for the themes)
![tmtheme](https://cloud.githubusercontent.com/assets/8791438/19618133/c27a23ac-984a-11e6-8630-25ffadcf77c1.png)

I've read allot of sources and documentations including [vscode javascript syntax](https://github.com/Microsoft/vscode/tree/master/extensions/javascript/syntaxes), [vscode theme samples](https://github.com/Microsoft/vscode-extension-samples/tree/master/theme-sample) and [vscode defaults scopes](https://github.com/Microsoft/vscode/tree/master/extensions/theme-defaults/themes).

All I can do is to update the theme packages for Atom and VSCode ....

**Comment by DavidStrada** [comment]
@NoHomey that's a bummer, thanks for your effort! I guess as close as possible is always good, so when you get a chance pls update the theme.
thanks again!
