### ISSUE TITLE
Github Color Updates

### ISSUE THREAD

**Issue by ryanponce** [RealGithub/RealGithub#2]
Thank you for creating this theme. I use it as my default theme everyday.

A few days ago, Github updated their colors. It seems like they increased the saturation overall. Do you have any plans to update this theme to match the new colors?

**Comment by NoHomey** [comment]
First, thanks. I don't plan to, at least not this month. I'm really busy and don't want to distract myself .... However I'm accepting pull requests.

**Comment by NoHomey** [comment]
Hello,

3 years have passed and I believe better themes exist now so I'm archiving the repo.

I'm sorry for abandoning the repo.
